[package]
name = "mime_multipart"
version = "0.5.0"
description = "MIME multipart parsing, construction, and streaming"
authors = ["Mike Dilger <mike@optcomp.nz>"]
readme = "README.md"
repository = "https://github.com/mikedilger/mime-multipart"
documentation = "https://mikedilger.github.io/mime-multipart"
license = "MIT OR Apache-2.0"
keywords = ["mime", "multipart", "mixed"]

[dependencies]
hyper = { version = "0.10", default-features = false }
mime = "0.2"
httparse = "1.2"
tempdir = "0.3"
textnonce = "0.5"
log = "0.3"
encoding = "0.2"
#buf-read-ext = "0.2"
buf-read-ext = { git = "ssh://git@github.com/ibLeo/buf-read-ext.git", branch = "master" }
